### ISSUE TITLE
it doesn't show in mod

### ISSUE THREAD

**Issue by huybui453** [modnext/mouseSteering#14]
### Version

1.1.0.0

### Game Version

1.14.0.0

### What happened?

i did it exactly as instructed but when i enter the game and enter the mod it doesn't show up
please help i really need it

**Comment by aaw3k** [comment]
If you can’t add the modification manually, you can download it directly from within the game. To do this, go to the game menu, then navigate to the `Downloadable Content` section » `Gameplay` (located at the very bottom). Select the `Mouse Steering` option or type `Mouse Steering` in the search field to install the modification.

**Comment by huybui453** [comment]
i searched for mouse steering but it doesnt show any mods


Vào Th 3, 29 thg 10, 2024 lúc 01:14 Sławek Jaskulski <
***@***.***> đã viết:

**Comment by aaw3k** [comment]
The modification is not available on consoles or in the cloud, nor is any other modification that alters `.lua` files.

**Comment by aaw3k** [comment]
The modification is not available on consoles or in the cloud, nor is any other modification that alters .lua files.
@huybui453 If you have the option `Show crossplay mods only` selected on the ModHub, please change it to `Show all mods`.

**Comment by aaw3k** [comment]
The modification is not available on consoles or in the cloud, nor is any other modification that alters .lua code.
@huybui453 If you have the option `Show crossplay mods only` selected on the ModHub, please change it to `Show all mods`.

**Comment by huybui453** [comment]
does it work on v1.3


Vào Th 3, 29 thg 10, 2024 lúc 01:42 Sławek Jaskulski <
***@***.***> đã viết:

**Comment by aaw3k** [comment]
No. The modification is compatible with version `1.14.0.0` or newer.
