### ISSUE TITLE
FS25

### ISSUE THREAD

**Issue by Antalela** [modnext/mouseSteering#20]
Hi there, we are big fans of your mode to FS22 the "Mouse Steering" one)) we want to ask if you have plans to work for FS25? Should we wait "Mouse Steering" for FS25...?

Thanks for your work.

**Comment by aaw3k** [comment]
At the moment, I don’t have the capacity to focus on the project. FS25 is one of the options I’m considering, but no decision has been made yet.

**Comment by Antalela** [comment]
I understand. Thank you for your concern

**Comment by Antalela** [comment]
I understand. Thank you for your concern
